#pragma once

#include "detail/CommonTypes.hpp"
#include "detail/scanner/ChildProcess.hpp"
#include "detail/scanner/RemotePluginScannerProcess.hpp"
#include "detail/scanner/PluginInstancing.hpp"
#include "detail/scanner/PluginScanTool.hpp"
#include "detail/scanner/PluginFormatManager.hpp"
#include "detail/scanner/RemoteScannerServer.hpp"
#include "detail/scanner/ScanOnlyRunner.hpp"
#include "detail/plugin-api/AudioPluginInstanceAPI.hpp"
#include "detail/plugin-api/AudioPluginCatalog.hpp"
#include "detail/plugin-api/AudioPluginScanning.hpp"
#include "detail/plugin-api/AudioPluginFormat.hpp"
#include "detail/plugin-api/AapUiHostDetailsExtension.hpp"
#include "detail/plugin-api/PluginStateChangeExtension.hpp"
#include "detail/plugin-api/AudioPluginHostingAPI.hpp"
#include "detail/plugin-api/AudioPluginNodeFeature.hpp"
