#pragma once

#include "detail/node-graph/AudioGraphDescriptor.hpp"
#include "detail/node-graph/AudioGraphBuiltInNodeFactory.hpp"
#include "detail/node-graph/AudioGraphRegistry.hpp"
#include "detail/node-graph/AudioGraphNode.hpp"
#include "detail/node-graph/AudioGraph.hpp"
#include "detail/node-graph/AudioGraphExtension.hpp"
#include "detail/node-graph/AudioBusesLayoutExtension.hpp"
#include "detail/node-graph/OutputRoutingExtension.hpp"
#include "detail/node-graph/AudioPluginNode.hpp"
#include "detail/node-graph/AudioPluginGraph.hpp"
#include "detail/node-graph/AudioPluginFullDAGraph.hpp"
#include "detail/builtin/BuiltInNodeTypes.hpp"
#include "detail/builtin/GainNode.hpp"
