var searchData=
[
  ['parameterenumeration_0',['ParameterEnumeration',['../d7/ded/structremidy_1_1ParameterEnumeration.html',1,'remidy']]],
  ['parametereventbase_1',['ParameterEventBase',['../d4/de0/classremidy_1_1ParameterEventBase.html',1,'remidy']]],
  ['parametereventbase_3c_20void_20_3e_2',['ParameterEventBase&lt; void &gt;',['../d4/de0/classremidy_1_1ParameterEventBase.html',1,'remidy']]],
  ['parametereventbase_3c_20void_2c_20pernotecontrollercontexttypes_2c_20uint32_5ft_2c_20uint32_5ft_2c_20double_20_3e_3',['ParameterEventBase&lt; void, PerNoteControllerContextTypes, uint32_t, uint32_t, double &gt;',['../d4/de0/classremidy_1_1ParameterEventBase.html',1,'remidy']]],
  ['parametereventbase_3c_20void_2c_20plugintiminginfochange_20_3e_4',['ParameterEventBase&lt; void, PluginTimingInfoChange &gt;',['../d4/de0/classremidy_1_1ParameterEventBase.html',1,'remidy']]],
  ['parametereventbase_3c_20void_2c_20uint32_5ft_2c_20double_20_3e_5',['ParameterEventBase&lt; void, uint32_t, double &gt;',['../d4/de0/classremidy_1_1ParameterEventBase.html',1,'remidy']]],
  ['parametermetadata_6',['ParameterMetadata',['../d1/d0d/structuapmd__plugin__hosting_1_1ParameterMetadata.html',1,'uapmd_plugin_hosting']]],
  ['parameternamedvalue_7',['ParameterNamedValue',['../d1/dc8/structuapmd__plugin__hosting_1_1ParameterNamedValue.html',1,'uapmd_plugin_hosting']]],
  ['parameterupdate_8',['ParameterUpdate',['../d4/d41/structuapmd__app_1_1ParameterUpdate.html',1,'uapmd_app']]],
  ['path_20resolution_9',['File Path Resolution',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md49',1,'']]],
  ['pernotecontrollercontext_10',['PerNoteControllerContext',['../d1/db8/structremidy_1_1PerNoteControllerContext.html',1,'remidy']]],
  ['persistence_11',['Track Volume Persistence',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md6',1,'']]],
  ['persistence_20behavior_12',['Current Graph Persistence Behavior',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md7',1,'']]],
  ['persistence_20notes_13',['Generic Graph Persistence Notes',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md15',1,'']]],
  ['playbackengineextension_14',['PlaybackEngineExtension',['../d8/d4e/classuapmd_1_1PlaybackEngineExtension.html',1,'uapmd']]],
  ['plugin_20node_15',['Example: Plugin Node',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md27',1,'']]],
  ['plugin_20node_20object_16',['plugin node object',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md36',1,'Legacy Linear Plugin Node Object'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md37',1,'Plugin Node Object']]],
  ['pluginaudiobuses_17',['PluginAudioBuses',['../d3/d8b/classremidy_1_1PluginAudioBuses.html',1,'remidy']]],
  ['pluginbundlepool_18',['PluginBundlePool',['../de/d6f/classremidy_1_1PluginBundlePool.html',1,'remidy']]],
  ['plugincatalog_19',['PluginCatalog',['../d8/ddc/classremidy_1_1PluginCatalog.html',1,'remidy']]],
  ['plugincatalogentry_20',['PluginCatalogEntry',['../d7/d03/classremidy_1_1PluginCatalogEntry.html',1,'remidy']]],
  ['pluginextensibility_21',['PluginExtensibility',['../d9/d46/classremidy_1_1PluginExtensibility.html',1,'remidy']]],
  ['pluginextensibility_3c_20pluginformat_20_3e_22',['PluginExtensibility&lt; PluginFormat &gt;',['../d9/d46/classremidy_1_1PluginExtensibility.html',1,'remidy']]],
  ['pluginextensibility_3c_20plugininstance_20_3e_23',['PluginExtensibility&lt; PluginInstance &gt;',['../d9/d46/classremidy_1_1PluginExtensibility.html',1,'remidy']]],
  ['pluginformat_24',['PluginFormat',['../d2/d58/classremidy_1_1PluginFormat.html',1,'remidy']]],
  ['pluginformatclap_25',['PluginFormatCLAP',['../d9/d2e/classremidy_1_1PluginFormatCLAP.html',1,'remidy']]],
  ['pluginformatlv2_26',['PluginFormatLV2',['../da/d4b/classremidy_1_1PluginFormatLV2.html',1,'remidy']]],
  ['pluginformatmanager_27',['PluginFormatManager',['../d3/d36/classuapmd__plugin__hosting_1_1PluginFormatManager.html',1,'uapmd_plugin_hosting']]],
  ['pluginformatvst3_28',['PluginFormatVST3',['../de/d25/classremidy_1_1PluginFormatVST3.html',1,'remidy']]],
  ['plugininstance_29',['PluginInstance',['../d3/dcc/classremidy_1_1PluginInstance.html',1,'remidy']]],
  ['plugininstanceaapext_30',['PluginInstanceAAPExt',['../d8/d5c/classremidy_1_1PluginInstanceAAPExt.html',1,'remidy']]],
  ['plugininstanceconfig_31',['PluginInstanceConfig',['../d5/dba/structuapmd__app_1_1AppModel_1_1PluginInstanceConfig.html',1,'uapmd_app::AppModel']]],
  ['plugininstanceresult_32',['PluginInstanceResult',['../d4/d06/structuapmd__app_1_1AppModel_1_1PluginInstanceResult.html',1,'uapmd_app::AppModel']]],
  ['plugininstancestate_33',['PluginInstanceState',['../d6/dfc/structuapmd__app_1_1AppModel_1_1PluginInstanceState.html',1,'uapmd_app::AppModel']]],
  ['plugininstancing_34',['PluginInstancing',['../d2/d61/classuapmd__plugin__hosting_1_1PluginInstancing.html',1,'uapmd_plugin_hosting']]],
  ['plugininstantiationoptions_35',['PluginInstantiationOptions',['../d2/d8d/structremidy_1_1PluginFormat_1_1PluginInstantiationOptions.html',1,'remidy::PluginFormat']]],
  ['pluginparameter_36',['PluginParameter',['../d7/dd4/classremidy_1_1PluginParameter.html',1,'remidy']]],
  ['pluginparametersupport_37',['PluginParameterSupport',['../d4/dfc/classremidy_1_1PluginParameterSupport.html',1,'remidy']]],
  ['pluginpresetssupport_38',['PluginPresetsSupport',['../d3/d34/classremidy_1_1PluginPresetsSupport.html',1,'remidy']]],
  ['pluginscanning_39',['PluginScanning',['../db/d22/classremidy_1_1PluginScanning.html',1,'remidy']]],
  ['pluginscanobserver_40',['PluginScanObserver',['../df/d0f/structuapmd__plugin__hosting_1_1PluginScanObserver.html',1,'uapmd_plugin_hosting']]],
  ['pluginscantool_41',['PluginScanTool',['../dd/d09/classuapmd__plugin__hosting_1_1PluginScanTool.html',1,'uapmd_plugin_hosting']]],
  ['pluginstateresult_42',['PluginStateResult',['../da/d5b/structuapmd__app_1_1AppModel_1_1PluginStateResult.html',1,'uapmd_app::AppModel']]],
  ['pluginstatesupport_43',['PluginStateSupport',['../db/d36/classremidy_1_1PluginStateSupport.html',1,'remidy']]],
  ['plugintiminginfochange_44',['PluginTimingInfoChange',['../d6/dd1/structremidy_1_1PluginTimingInfoChange.html',1,'remidy']]],
  ['pluginuisupport_45',['PluginUISupport',['../da/d13/classremidy_1_1PluginUISupport.html',1,'remidy']]],
  ['port_46',['port',['../d1/d6c/classuapmd__app_1_1McpServer.html#a2962edfd707789754f419098edc6e6f9',1,'uapmd_app::McpServer']]],
  ['positioning_47',['positioning',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md40',1,'Example 1: Absolute Positioning'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md41',1,'Example 2: Track-Anchored Positioning'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md42',1,'Example 3: Clip-Anchored Positioning']]],
  ['positioning_20examples_48',['Positioning Examples',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md39',1,'']]],
  ['presetinfo_49',['PresetInfo',['../d4/d06/classremidy_1_1PresetInfo.html',1,'remidy']]],
  ['presetsmetadata_50',['PresetsMetadata',['../df/d80/structuapmd__plugin__hosting_1_1PresetsMetadata.html',1,'uapmd_plugin_hosting']]],
  ['processmainthreadqueue_51',['processMainThreadQueue',['../d1/d6c/classuapmd__app_1_1McpServer.html#a560e8458d44b39727240ddd10059f4a4',1,'uapmd_app::McpServer']]],
  ['project_20file_20format_20documentation_20ai_20slop_52',['UAPMD Project File Format Documentation (AI slop)',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html',1,'']]],
  ['projectarchive_53',['ProjectArchive',['../df/daa/classuapmd_1_1ProjectArchive.html',1,'uapmd']]],
  ['projectarchiveextractresult_54',['ProjectArchiveExtractResult',['../d1/dbc/structuapmd_1_1ProjectArchiveExtractResult.html',1,'uapmd']]],
  ['projectaudiosourcesnapshot_55',['ProjectAudioSourceSnapshot',['../da/d2d/structuapmd_1_1ProjectAudioSourceSnapshot.html',1,'uapmd']]],
  ['projectclipsnapshot_56',['ProjectClipSnapshot',['../d9/d17/structuapmd_1_1ProjectClipSnapshot.html',1,'uapmd']]],
  ['projectdocumentevent_57',['ProjectDocumentEvent',['../dd/d94/classuapmd_1_1ProjectDocumentEvent.html',1,'uapmd']]],
  ['projectdocumenteventdetails_58',['ProjectDocumentEventDetails',['../dd/d6a/classuapmd_1_1ProjectDocumentEventDetails.html',1,'uapmd']]],
  ['projectdocumenteventdispatcher_59',['ProjectDocumentEventDispatcher',['../dd/dbe/classuapmd_1_1ProjectDocumentEventDispatcher.html',1,'uapmd']]],
  ['projectdocumenteventlistener_60',['ProjectDocumentEventListener',['../df/d29/classuapmd_1_1ProjectDocumentEventListener.html',1,'uapmd']]],
  ['projectdocumenteventsource_61',['ProjectDocumentEventSource',['../dc/d65/classuapmd_1_1ProjectDocumentEventSource.html',1,'uapmd']]],
  ['projectdocumentview_62',['ProjectDocumentView',['../df/d3f/classuapmd_1_1ProjectDocumentView.html',1,'uapmd']]],
  ['projectresult_63',['projectresult',['../d3/de1/structuapmd__app_1_1AppModel_1_1ProjectResult.html',1,'uapmd_app::AppModel::ProjectResult'],['../d8/de9/structuapmd_1_1TimelineFacade_1_1ProjectResult.html',1,'uapmd::TimelineFacade::ProjectResult']]],
  ['projectsaveoptions_64',['ProjectSaveOptions',['../df/d31/structuapmd_1_1TimelineFacade_1_1ProjectSaveOptions.html',1,'uapmd::TimelineFacade']]],
  ['projectserializationextension_65',['ProjectSerializationExtension',['../d5/d0b/classuapmd_1_1ProjectSerializationExtension.html',1,'uapmd']]],
  ['projectserializationreadcontext_66',['ProjectSerializationReadContext',['../dc/d81/classuapmd_1_1ProjectSerializationReadContext.html',1,'uapmd']]],
  ['projectserializationwritecontext_67',['ProjectSerializationWriteContext',['../d1/df7/classuapmd_1_1ProjectSerializationWriteContext.html',1,'uapmd']]],
  ['projecttracksnapshot_68',['ProjectTrackSnapshot',['../de/d5c/structuapmd_1_1ProjectTrackSnapshot.html',1,'uapmd']]],
  ['properties_69',['Properties',['../dc/d61/structuapmd_1_1AudioFileReader_1_1Properties.html',1,'uapmd::AudioFileReader']]],
  ['pseudo_20nodes_70',['Reserved Pseudo-Nodes',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md23',1,'']]]
];
