var searchData=
[
  ['channel_20merger_20node_0',['Example: Channel Merger Node',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md25',1,'']]],
  ['channel_20splitter_20node_1',['Example: Channel Splitter Node',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md26',1,'']]],
  ['childprocess_2',['ChildProcess',['../dc/da6/classremidy__tooling_1_1ChildProcess.html',1,'remidy_tooling']]],
  ['clip_20anchored_20positioning_3',['Example 3: Clip-Anchored Positioning',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md42',1,'']]],
  ['clip_20object_4',['Clip Object',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md8',1,'']]],
  ['clipaddresult_5',['ClipAddResult',['../dc/d61/structuapmd_1_1TimelineFacade_1_1ClipAddResult.html',1,'uapmd::TimelineFacade']]],
  ['clipdata_6',['ClipData',['../d4/d9f/structuapmd_1_1ClipData.html',1,'uapmd']]],
  ['clipinfo_7',['ClipInfo',['../d6/d90/structuapmd_1_1MidiClipReader_1_1ClipInfo.html',1,'uapmd::MidiClipReader']]],
  ['clipmanager_8',['ClipManager',['../de/dab/classuapmd_1_1ClipManager.html',1,'uapmd']]],
  ['clipmarker_9',['ClipMarker',['../d6/d34/structuapmd_1_1ClipMarker.html',1,'uapmd']]],
  ['clipsnapshot_10',['ClipSnapshot',['../d4/d17/structuapmd_1_1ClipManager_1_1ClipSnapshot.html',1,'uapmd::ClipManager']]],
  ['complete_20example_11',['complete example',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md44',1,'Complete Example'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md28',1,'Complete Example']]],
  ['configuration_12',['Configuration',['../de/d3e/structuapmd_1_1AudioIODeviceManager_1_1Configuration.html',1,'uapmd::AudioIODeviceManager']]],
  ['configurationrequest_13',['ConfigurationRequest',['../d3/d3b/structremidy_1_1PluginInstance_1_1ConfigurationRequest.html',1,'remidy::PluginInstance']]],
  ['connection_20fields_14',['Connection Fields',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md20',1,'']]],
  ['connection_20object_15',['Connection Object',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md19',1,'']]],
  ['considerations_16',['Sample Rate Considerations',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md48',1,'']]],
  ['containerwindow_17',['ContainerWindow',['../d7/d22/classremidy_1_1gui_1_1ContainerWindow.html',1,'remidy::gui']]],
  ['contentbounds_18',['ContentBounds',['../d7/d7f/structuapmd_1_1TimelineFacade_1_1ContentBounds.html',1,'uapmd::TimelineFacade']]],
  ['convertresult_19',['ConvertResult',['../da/d3e/structuapmd_1_1SmfConverter_1_1ConvertResult.html',1,'uapmd::SmfConverter']]],
  ['current_20graph_20persistence_20behavior_20',['Current Graph Persistence Behavior',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md7',1,'']]],
  ['current_20implemented_20graph_20object_21',['Current Implemented Graph Object',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md31',1,'']]]
];
