var searchData=
[
  ['naming_0',['Node Type Naming',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md18',1,'']]],
  ['nativeplugininstancehandleextension_1',['nativeplugininstancehandleextension',['../d8/dcd/classuapmd_1_1NativePluginInstanceHandleExtension.html',1,'uapmd::NativePluginInstanceHandleExtension'],['../d8/d6b/classremidy_1_1NativePluginInstanceHandleExtension.html',1,'remidy::NativePluginInstanceHandleExtension']]],
  ['negative_20offset_2',['Example 4: Negative Offset',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md43',1,'']]],
  ['node_3',['node',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md25',1,'Example: Channel Merger Node'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md26',1,'Example: Channel Splitter Node'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md24',1,'Example: Gain Node'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md27',1,'Example: Plugin Node']]],
  ['node_20fields_4',['Node Fields',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md17',1,'']]],
  ['node_20object_5',['node object',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md36',1,'Legacy Linear Plugin Node Object'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md16',1,'Node Object'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md37',1,'Plugin Node Object']]],
  ['node_20type_20naming_6',['Node Type Naming',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md18',1,'']]],
  ['nodes_7',['Reserved Pseudo-Nodes',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md23',1,'']]],
  ['non_20goals_20for_20version_201_8',['Non-Goals for Version 1',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md30',1,'']]],
  ['notes_9',['notes',['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md15',1,'Generic Graph Persistence Notes'],['../d6/d9c/md_source_2uapmd-data_2include_2uapmd-data_2detail_2project_2UapmdProjectFile.html#autotoc_md45',1,'Implementation Notes']]]
];
